version: "3.7"

services:
  sh:
    build:
      context: .
      args: 
        - NVIM_FILE=${NVIM_FILE}
        - GO_DL_URL=${GO_DL_URL}
        #args: ["NVIM_FILE=${NVIM_FILE}", "GO_DL_URL=${GO_DL_URL}"]
    init: true
    tty: true
    extra_hosts:
      - "archive.ubuntu.com:160.26.2.187"
    working_dir: ${APP_DIR}
    restart: always
    volumes:
      - deve-home:/root
      - "${APP_DIR}:${APP_DIR}"
      - ./init.vim:/root/.config/nvim/init.vim
        #network_mode: "host"
        #ports:
        #  - "49900:49900"
    logging:
      driver: journald
      options:
        tag: "{{.Name}}"
volumes:
  deve-home:
    driver: local
